research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

# Claude Terminal Assistant Tasks
process_command_task:
  description: >
    Process the user's terminal command or query: "{user_command}"
    Understand the intent and determine which specialist agent to delegate to.
    Current working directory is: {cwd}
    User context: {user_context}
  expected_output: >
    A clear and helpful response to the user's query, with the appropriate action taken.
  agent: terminal_commander

navigate_files_task:
  description: >
    Navigate or explore the file system based on this request: "{file_request}"
    Current working directory: {cwd}
  expected_output: >
    Details about the requested files or directories, including contents, structure, or file contents
    if requested to read a file.
  agent: file_navigator

execute_code_task:
  description: >
    Execute this code or command: "{code_snippet}"
    Current working directory: {cwd}
    Make sure to validate the command for safety before execution.
  expected_output: >
    The output of the executed code or command, or an explanation of why it couldn't be executed
    if there were safety concerns.
  agent: code_executor

web_search_task:
  description: >
    Research this topic online: "{search_query}"
    Find relevant and up-to-date information from search engines or specific websites.
  expected_output: >
    A concise answer to the search query, directly extracting and summarizing key
    details and structured data (e.g., for a weather query, this means specific
    temperature, conditions, wind speed, humidity). Cite sources if appropriate.
    If specific details are requested, provide them directly, not just a general summary.
  agent: web_researcher
