research_task:
  description: >
    Conduct thorough research on the topic: '{topic}'.
    Identify key developments, current trends, significant factual information,
    and notable opinions or analyses.
    Ensure information is relevant to the current year: {current_year}.
  expected_output: >
    A concise, well-organized list of 10-15 bullet points summarizing the most relevant findings

reporting_task:
  description: >
    Based on the research findings about '{topic}',
    create a comprehensive and well-structured report.
    Expand each key finding into a detailed section, providing supporting information,
    analysis, and examples where appropriate.
  expected_output: >
    A fully fledged report in clean markdown format

process_command_task:
  description: >
    Process the user's terminal command or query: '{user_command}'
    Current working directory: {cwd}
    User context: {user_context}
    Command history context: {claude_context}
    
    Analyze the command and coordinate with specialist agents as needed.
    Provide clear, helpful responses and execute the requested operations safely.
  expected_output: >
    A clear response addressing the user's command with appropriate action taken

navigate_files_task:
  description: >
    Handle file system navigation and operations for: '{file_request}'
    Current working directory: {cwd}
    
    Perform the requested file operations safely and provide clear feedback.
  expected_output: >
    Clear information about the file operation results

execute_code_task:
  description: >
    Execute the following code or command safely: '{code_snippet}'
    Current working directory: {cwd}
    
    Run the code in a secure environment and provide execution results.
  expected_output: >
    Execution results with any output, errors, or status information

web_search_task:
  description: >
    Research the following query using web sources: '{search_query}'
    
    Find accurate, current information and provide a comprehensive summary.
  expected_output: >
    A well-researched summary with key findings and relevant information

analyze_pdf_task:
  description: >
    Analyze the PDF document located at '{pdf_path}'.
    Extract key information, summarize its content, or answer specific questions
    based on the user's request: '{user_query_about_pdf}'
    
    If the PDF is large, consider breaking it down into manageable chunks.
  expected_output: >
    A comprehensive analysis addressing the user's specific query about the PDF
  agent: pdf_document_analyst

translate_text_task:
  description: >
    Translate the given text: '{text_to_translate}'
    From: {source_language}
    To: {target_language}
    
    Additional context: {translation_context}
    
    Provide an accurate translation with cultural sensitivity and linguistic appropriateness.
    Include explanations of cultural nuances when relevant.
  expected_output: >
    An accurate translation with cultural context and linguistic notes when appropriate
  agent: multilingual_translator

analyze_csv_task:
  description: >
    Analyze the CSV file located at {csv_path}.
    
    Your analysis should include:
    1. Data structure examination (columns, data types, row count)
    2. Statistical summary of numerical columns
    3. Identification of missing or anomalous data
    4. Key patterns and insights
    5. Data quality assessment
    
    Provide recommendations for data processing or further analysis if applicable.
    Share insights abundantly for collective benefit.
  expected_output: >
    A comprehensive CSV analysis report including:
    - Data structure overview
    - Statistical summaries
    - Quality assessment
    - Key insights and patterns
    - Recommendations for next steps
  agent: csv_data_analyst

monitor_balance_task:
  description: >
    Monitor and assess balance across the specified focus areas: {focus_areas}.
    
    Your assessment should cover:
    1. Current state analysis of each focus area
    2. Identification of imbalances or stress points
    3. Interconnections between different areas
    4. Nature's Way principles application
    5. Actionable recommendations for improvement
    
    Apply holistic thinking and abundance mindset in your recommendations.
  expected_output: >
    A balance assessment report containing:
    - Current state analysis
    - Identified imbalances
    - Interconnection mapping
    - Actionable recommendations
    - Wellness improvement strategies
  agent: balance_monitor

architect_solution_task:
  description: >
    Design a software architecture solution for the given requirements: {project_requirements}.
    
    Your design should include:
    1. System architecture overview
    2. Component design and interactions
    3. Technology stack recommendations
    4. Scalability and performance considerations
    5. Security and reliability measures
    6. Implementation roadmap
    
    Apply abundance principles by creating reusable, well-documented solutions.
  expected_output: >
    A detailed architectural design document including:
    - Architecture diagrams and patterns
    - Component specifications
    - Technology recommendations
    - Implementation guidance
    - Best practices and considerations
  agent: software_architect

systems_analysis_task:
  description: >
    Apply systems thinking to analyze the given context: {system_context}.
    
    Your analysis should identify:
    1. System boundaries and components
    2. Relationships and interdependencies
    3. Feedback loops and dynamics
    4. Leverage points for change
    5. Emergent behaviors and patterns
    6. Potential unintended consequences
    
    Provide insights that contribute to collective understanding and wisdom.
  expected_output: >
    A systems analysis report containing:
    - System mapping and structure
    - Relationship analysis
    - Leverage point identification
    - Emergent behavior insights
    - Recommendations for system optimization
  agent: systems_thinker
